# Generated by Django 4.2.5 on 2024-01-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=50)),
                ("data_of_joining", models.DateField()),
                ("attendance", models.BooleanField(default=False)),
                ("attendance_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
