# Generated by Django 4.2.5 on 2024-01-04 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="data_of_joining",
            new_name="date_of_joining",
        ),
    ]
